# Generated by Django 4.2.11 on 2024-04-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
